[package]
name = "remora-etcher-image-application-transport-cli"
description = "clap subcommands exposing the image application service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
remora-etcher-image = { path = "../remora-etcher-image" }
remora-etcher-format = { path = "../remora-etcher-format" }
clap.workspace = true
error-stack.workspace = true
thiserror.workspace = true
