[package]
name = "remora-etcher-squashfs-adapter-backhand"
description = "Concrete SquashfsAdapter: wraps backhand"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
remora-etcher-squashfs = { path = "../remora-etcher-squashfs" }
error-stack.workspace = true
backhand = "0.25"
