[package]
name = "remora-squashfs-application-transport-cli"
description = "clap subcommands exposing the squashfs application service"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
remora-squashfs = { path = "../squashfs" }
remora-format = { path = "../format" }
remora-progress = { path = "../progress" }
clap.workspace = true
error-stack.workspace = true
tokio.workspace = true
tokio-util.workspace = true
