[package]
name = "remora-etcher-flash-application-transport-cli"
description = "clap command exposing the flash application service"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
remora-etcher-disk = { path = "../remora-etcher-disk" }
remora-etcher-flash = { path = "../remora-etcher-flash" }
remora-etcher-format = { path = "../remora-etcher-format" }
remora-etcher-progress = { path = "../remora-etcher-progress" }
clap.workspace = true
error-stack.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
